/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <string.h>
#include "stm32f401xx.h"

void delay(void)
{
	for (int i = 0; i < 1000000; ++i) {
		;
	}
}

static inline void vDoSpiGpioConf(void);
static inline void vDoSpiHandleConf(void);

static inline void vDoSpiGpioConf(void)
{
	TS_GPIO_CONFIG sSpiNssConf;
	sSpiNssConf.u8GpioPinNum = 12U;
	sSpiNssConf.u8GpioPinMode = GPIO_MODE_ALT_FUNC;
	sSpiNssConf.u8GpioPinOPType = GPIO_OUT_MODE_PP;
	sSpiNssConf.u8GpioPinPuPdControl = GPIO_PUPD_NU_ND;
	sSpiNssConf.u8GpioPinSpeed = GPIO_OUT_SPEED_VERY_HIGH;
	sSpiNssConf.u8GpioPinAltFunMode = 0x05;

	TS_GPIO_CONFIG sSpiSckConf;
	sSpiSckConf.u8GpioPinNum = 13U;
	sSpiSckConf.u8GpioPinMode = GPIO_MODE_ALT_FUNC;
	sSpiSckConf.u8GpioPinOPType = GPIO_OUT_MODE_PP;
	sSpiSckConf.u8GpioPinPuPdControl = GPIO_PUPD_NU_ND;
	sSpiSckConf.u8GpioPinSpeed = GPIO_OUT_SPEED_VERY_HIGH;
	sSpiSckConf.u8GpioPinAltFunMode = 0x05;

	TS_GPIO_CONFIG sSpiMisoConf;
	sSpiMisoConf.u8GpioPinNum = 14U;
	sSpiMisoConf.u8GpioPinMode = GPIO_MODE_ALT_FUNC;
	sSpiMisoConf.u8GpioPinOPType = GPIO_OUT_MODE_PP;
	sSpiMisoConf.u8GpioPinPuPdControl = GPIO_PUPD_NU_ND;
	sSpiMisoConf.u8GpioPinSpeed = GPIO_OUT_SPEED_VERY_HIGH;
	sSpiMisoConf.u8GpioPinAltFunMode = 0x05;

	TS_GPIO_CONFIG sSpiMosiConf;
	sSpiMosiConf.u8GpioPinNum = 15U;
	sSpiMosiConf.u8GpioPinMode = GPIO_MODE_ALT_FUNC;
	sSpiMosiConf.u8GpioPinOPType = GPIO_OUT_MODE_PP;
	sSpiMosiConf.u8GpioPinPuPdControl = GPIO_PUPD_NU_ND;
	sSpiMosiConf.u8GpioPinSpeed = GPIO_OUT_SPEED_VERY_HIGH;
	sSpiMosiConf.u8GpioPinAltFunMode = 0x05;

	TS_GPIO_HANDLE sSpiNss;
	sSpiNss.psGpioBaseAddr = GPIOB;
	sSpiNss.sGpioPinConfig = &sSpiNssConf;

	TS_GPIO_HANDLE sSpiSck;
	sSpiSck.psGpioBaseAddr = GPIOB;
	sSpiSck.sGpioPinConfig = &sSpiSckConf;

	TS_GPIO_HANDLE sSpiMiso;
	sSpiMiso.psGpioBaseAddr = GPIOB;
	sSpiMiso.sGpioPinConfig = &sSpiMisoConf;

	TS_GPIO_HANDLE sSpiMosi;
	sSpiMosi.psGpioBaseAddr = GPIOB;
	sSpiMosi.sGpioPinConfig = &sSpiMosiConf;


	vDoGpioPeriClockControl(GPIOB, true);

	vDoGpioIni(&sSpiNss);
	vDoGpioIni(&sSpiSck);
	vDoGpioIni(&sSpiMiso);
	vDoGpioIni(&sSpiMosi);
}

static inline void vDoSpiHandleConf(void)
{
	TS_SPI_CONFIG sSpiConf;
	sSpiConf.u8SpiDeviceMode = SPI_DEVICE_MODE_MASTER;
	sSpiConf.u8SpiBusConfig = SPI_BUS_CONFIG_FD;
	sSpiConf.u8SpiSclkSpeed = SPI_SPEED_PCLK_DIV256;
	sSpiConf.u8SpiDff = SPI_DFF_8BITS;
	sSpiConf.u8SpiCpol = SPI_CPOL_LOW;
	sSpiConf.u8SpiCpha = SPI_CPHA_LOW;
	sSpiConf.u8SpiSsm = SPI_SSM_SW;

	TS_SPI_HANDLE sSpiHandle;
	sSpiHandle.psSpiBaseAddr = SPI2;
	sSpiHandle.psSpiConfig = &sSpiConf;

	vDoSpiPeriClockControl(SPI2, true);

	vDoSpiIni(&sSpiHandle);
}

int main(void)
{
	char user_data[] = "Hello world!!!";

	vDoSpiGpioConf();

	TS_SPI_CONFIG sSpiConf;
	sSpiConf.u8SpiDeviceMode = SPI_DEVICE_MODE_MASTER;
	sSpiConf.u8SpiBusConfig = SPI_BUS_CONFIG_FD;
	sSpiConf.u8SpiSclkSpeed = SPI_SPEED_PCLK_DIV256;
	sSpiConf.u8SpiDff = SPI_DFF_8BITS;
	sSpiConf.u8SpiCpol = SPI_CPOL_LOW;
	sSpiConf.u8SpiCpha = SPI_CPHA_LOW;
	sSpiConf.u8SpiSsm = SPI_SSM_SW;

	TS_SPI_HANDLE sSpiHandle;
	sSpiHandle.psSpiBaseAddr = SPI2;
	sSpiHandle.psSpiConfig = &sSpiConf;
	sSpiHandle.eStateSpiBus = eStateSpiBusReady;

	vDoSpiPeriClockControl(SPI2, true);

	vDoSpiIni(&sSpiHandle);

	vDoSpiIrqConfig(NVIC, IRQ_NO_SPI2, NVIC_IRQ_PRI15, true);

	vDoSpiSsiControl(SPI2, true);

	vDoSpiPeriControl(SPI2, true);

	while(1)
	{
		vDoSpiSendDataIt(&sSpiHandle, (uint8_t*) user_data, strlen(user_data));
		delay();
	}
}

void vDoSpiEventCallback(TS_SPI_HANDLE *psSpiHandle, TE_SPI_STATUS_EVENT eSpiStatusEvent)
{

}

void SPI2_IRQHandler(void)
{
	TS_SPI_CONFIG sSpiConf;
		sSpiConf.u8SpiDeviceMode = SPI_DEVICE_MODE_MASTER;
		sSpiConf.u8SpiBusConfig = SPI_BUS_CONFIG_FD;
		sSpiConf.u8SpiSclkSpeed = SPI_SPEED_PCLK_DIV256;
		sSpiConf.u8SpiDff = SPI_DFF_8BITS;
		sSpiConf.u8SpiCpol = SPI_CPOL_LOW;
		sSpiConf.u8SpiCpha = SPI_CPHA_LOW;
		sSpiConf.u8SpiSsm = SPI_SSM_SW;

		TS_SPI_HANDLE sSpiHandle;
		sSpiHandle.psSpiBaseAddr = SPI2;
		sSpiHandle.psSpiConfig = &sSpiConf;
		sSpiHandle.eStateSpiBus = eStateSpiBusReady;
	vDoSpiIrqHandling(EXTI, &sSpiHandle);
}
